### PR TITLE
Switch to github actions for CI

### PR DESCRIPTION
**Pull request by purcell**
This is a work in progress, because cask appears broken currently.

### CODE REVIEW

**Comment by purcell** [comment]
(Actions won't start running here automatically, but they are running for this branch in my fork, which is how I know they are broken.)

**Comment by asok** [comment]
> This is a work in progress, because cask appears broken currently.

Do you think it's an upstream issue? I tried to google for `"Symbol's value as variable is void: dependency"` but no avail.

**Comment by purcell** [comment]
I'm not really sure, but didn't have time to dig into it thoroughly. I know that cask has had some issues recently, so it's unclear what the status of it and the `setup-cask` action are. There's also [makem.sh](https://github.com/alphapapa/makem.sh) which can install deps from a cask file, but I haven't used that before myself.

**Comment by asok** [comment]
It seems that travis is also not passing. I will merge this in and try to debug.

**Pull request merged**
