### PR TITLE
Add Rails 5.1 webpack integration

### PR DESCRIPTION
**Pull request by a3ammar**
Hi,
Webpacker puts every component under `app/javascript/packs/` and all its configurations under
`config/webpack/`.

This adds:
- `projectile-rails-goto-package` that opens `package.json` bound as `C-c r g p`.
- `projectile-rails-find-component` that lists the project components bound as `C-c r w`.
- `projectile-rails-find-webpack` that lists webpack configurations bound as `C-r r W`.
- And tests for those methods.

I'm not sure about the keybinding, especially the one for the configuration finder but I couldn't think of a better one, do you have any recommendation?

### CODE REVIEW

**Comment by asok** [comment]
Hi, I really appreciate your effort.

But to be honest I'm quit unsure if we should merge this functionality. This is certainly useful for people using webpacker. But the majority of the projectile-rails users do not use it. I don't use it right now and probably will not use it in foreseeable future. By merging it we would need to maintain this functionality.

@a3ammar maybe it makes more sense to create a package named webpacker.el (or whatever else) that would be based on projectile-rails. What do you think?
@Silex what's your opinion on that?

**Comment by Silex** [comment]
Mmm... I don't know about webpack yet so it's hard to comment on it.

The changes don't look too intrusive, so I guess it's not that big of a deal to merge this, but at the same time it's also easy to make these changes as a `projectile-rails-webpack` package that depends on `projectile-rails` (even if that sounds a bit silly).

So really it's up to you, if I was to decide I'd probably merge this if @a3ammar is ok to step up for maintaining that part of projectile-rails if need be.

**Comment by a3ammar** [comment]
Right now webpacker is very new and not many are using it but with time this will change, I think. It's kind of an overkill making them into a separate package.

I have no issue maintaining this, so it's your call.

**Comment by asok** [comment]
> Right now webpacker is very new and not many are using it but with time this will change, I think.

Having a brief look at it - indeed it looks very promising. But there are a lot of useful gems out there that are not part of rails. If we would like to support all of them soon we would be left without free slots in the keymap to assign shortcuts :)

I'm thinking whether it makes more sense to define and add kebinding for the new commands [here](https://github.com/asok/projectile-rails/blob/48db17d5e9b191ea974ef90dae20651606347651/projectile-rails.el#L1460-L1463) but only if webpacker is in use. @a3ammar is it possible to distinguish a repo that uses webpacker gem and one that does not? Do you think that by simply looking for the presence of file`package.json` it is sufficient?

**Comment by a3ammar** [comment]
> But there are a lot of useful gems out there that are not part of rails. If we would like to support all of them soon we would be left without free slots in the keymap to assign shortcuts :)

I agree, but webpacker _is_ part of Rails though, version 5.1 has `--webpack` as command line argument.

> is it possible to distinguish a repo that uses webpacker gem and one that does not? Do you think that by simply looking for the presence of file `package.json` it is sufficient?

`package.json` can also be in projects that don't necessary depend on webpacker but uses `npm` for other reasons. I belive the best way to identify if webpacker is present is to look for `config/webpack/` directory.

**Comment by asok** [comment]
> I agree, but webpacker is part of Rails though, version 5.1 has --webpack as command line argument.

Sorry then. I've totally missed that. If that's the case I think it's totally fine and desired to merge in your PR. Thanks again.

**Pull request merged**
