### PR TITLE
Add helpers to find serializers

### PR DESCRIPTION
**Pull request by totallymike**
API-based Rails applications depend often on serializers instead of views.  Furthermore, Rails 5 is including Rails API along with ActiveModel::Serializers out of the box.

I threw together a couple functions to help me find them rapidly, and I thought I'd offer them upstream.

Admittedly, this is so far rather naive.  It only has the parts that are directly relevant to me, i.e. the finders.  It also doesn't include default keymaps--I'm using evil at the moment so I have no opinion on what they should be.

What can I add to this to make it helpful and fit into the current infrastructure?

### CODE REVIEW

**Comment by asok** [comment]
Thanks!
But now comes the hardest part - what keybinding should be used for this?

**Comment by totallymike** [comment]
I've been dreading that question! 

A brief glance from my phone suggests 'z/Z' are unused?

**Comment by asok** [comment]
"z" sounds good

**Comment by totallymike** [comment]
Thanks for merging!

**Pull request merged**
